spring:
  datasource:
    url: jdbc:postgresql://192.168.151.5:5432/geekmarket
    username: geek
    password: 123geek123
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog-master.xml